### ISSUE TITLE
Some Documentation fixes

### ISSUE THREAD

**Issue by Bas-Man** [zineland/zineland.github.io#1]
Hi,
I am thinking about taking a look at the documentation and making fixes as I find them.
But I have a question about which commit ID I should base from.
Should I use `main` or [e9850b2c2](https://github.com/zineland/zineland.github.io/tree/e9850b2c2deb44e8ffe99846a8afccf91373b1140) as the base of any changes I want to submit?

**Comment by Folyd** [comment]
Thanks, @Bas-Man. I thinks you can just based on main branch. BTW, [e9850b2c2](https://github.com/zineland/zineland.github.io/tree/e9850b2c2deb44e8ffe99846a8afccf91373b1140) is 404.
